[package]
name = "runtime_adversarial_abilities"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "722ac4fcf4841346c91775f596c4ce23fb7fbd0f" }
animacraft_v8_runtime = { local = "../.." }

[addresses]
runtime_adversarial_abilities = "0x0"
